### ISSUE TITLE
Beacon Sync progress

### ISSUE THREAD

**Issue by ogenev** [ethereum/trin#1006]
This is a tracking issue of the current progress of the beacon sync implementation.

### Tasks
- [ ] Update `LightClientFinalityUpdate` to include `finalized_slot` instead of `signature_slot` in the content key.
- [ ] Update and deploy Trin beacon bridge to serve the new lc finality data.
- [ ] Modify light client crate to not require LC finality update for the current slot on sync startup.
- [ ] Modify light client portal interface strategy for requesting LC finality update every slot (with `finalized_slot` as content key) when tracking the head of the chain.
- [ ] Support building a batch of `LightClientUpdate` records as a response to a period range request.
  - May require a heavy refactoring in overlay service?
  - Special database for the beacon network?
- [ ] Re-evaluate the bridge strategy for pushing `LightClientUpdate` data into the network in real-time?

**Comment by pipermerriam** [comment]
Reguarding the "special database for beacon network"...  sqlite is quite powerful and will allow a schema'd database with complex queries...  I believe that our use of rocksdb is a bit of cargo-cult leftover from execution clients storing all of the state and needing blazing fast read-write access.  My intuition is that in our usage pattern the database read/write speeds are unlikely to be the bottleneck.
