### ISSUE TITLE
Testnet Details

### ISSUE THREAD

**Issue by njgheorghita** [ethereum/trin#118]
This issue is to track a discussion around the initial details for the inaugural trin testnet. Once the open questions are settled, this will be moved to a milestone with accompanying issues to track progress. The lists below are just a starting point - feel free to make any suggestions to add/remove/edit and I'll update the list accordingly.

# Goal
Establishing a test network that is purely the overlay network (ping /ping/find/found) with nodes able to build and maintain their routing tables. That lets us start deploying longer lived nodes and to iterate in a production-like environment.

# Open Questions
- [x] How many nodes do we want in the testnet?
  - 32 for now - and capacity to expand to 256 once we start serving real content
- [x] What's the best way to monitor testnet? Would a dashboard of some kind be useful?
- [x] What kind of cloud resources are required? How much storage should each node provide?
- [x] Deployment scripts. [Fab](http://www.fabfile.org/)? K8s?
- [ ] Updating testnet nodes - Do we want to establish a trin release cycle with some regular cadence (2 / 3 / 4 weeks)?

# Todos
- [x] Request cloud resources from the EF
- [ ] Complete v0.1 features & cut release
- [ ] Deploy testnet
- [ ] Monitor

# v0.1 features
- [x] #69 
- [ ] A (mock?) `FINDCONTENT`/`FOUNDCONTENT` request that will initiate a `uTP` transfer for an overlay network
- [ ] JSONRPC API support for [`ddht` utility endpoints](https://ddht.readthedocs.io/en/latest/jsonrpc.html#discovery-v5-1)
- [x] https://github.com/ethereum/trin/issues/109
- [x] https://github.com/ethereum/trin/issues/64
- [x] https://github.com/ethereum/trin/issues/113

**Comment by ogenev** [comment]
I would add managing the overlay routing table and OFFER/ACCEPT implementation in v0.1 features

**Comment by pipermerriam** [comment]
>  How large / small / varied data radius should they use?

Radius should typically be derived from the amount of storage a node chooses to offer the network.  While storage is not full, node advertises a 100% radius.  Once storage fills up, the node advertises a radius value equal to the distance of the *furthest* content the node is storing.

**Comment by pipermerriam** [comment]
> How many nodes do we want in the testnet?

I think we can go for 32 nodes as a starting point and expand to something like 256 at the point where we start dealing with actual content.

**Comment by pipermerriam** [comment]
>  What kind of cloud resources are required? How much storage should each node provide?

Lets go with 1GB of disk to start with the expectation that we'll drop that down to maybe ~200MB by the time we move towards launch.

**Comment by pipermerriam** [comment]
> What kind of cloud resources are required? How much storage should each node provide?

I'd like to aim for tiny and low end.  Slow disk.  1 CPU.  1GB ram.

**Comment by pipermerriam** [comment]
I would lay out these milestones

### Milestone A

- support PING/PONG/FINDNODES/FOUNDNODES messages.
- node responds to PING with PONG
- node responds to FINDNODES with FOUNDNODES with data from their routing table.
- node uses hardcoded bootnodes to bootstrap into the network
- node uses "recursive find nodes" algorithm to populate and maintain routing table
- node performs liveliness checks on routing table entries

### Milestone B

- support for FINDCONTENT/FOUNDCONTENT
- node has machinery for storing content on disk and retrieving it by `content-key`
- node responds to FINDCONTENT with FOUNDCONTENT with embedded payload (no uTP)
- we have some ability to pre-populate node databases with content

### Milestone C

- one of or both:
    - OFFER/ACCEPT + uTP
    - FINDCONTENT/FOUNDCONTENT + uTP

**Comment by njgheorghita** [comment]
Closing b/c testnet is up and features roadmap is written in alpha network milestone
