### ISSUE TITLE
Testing Structure

### ISSUE THREAD

**Issue by njgheorghita** [ethereum/trin#185]
# Proposed direction of trin's testing structure

## Unit tests
- If it can be written as a unit test, it should be.

## `tests` module
- Integration tests for trin-specific functionality 
  - Runs `ethportal-peertest` against trin (or a group of trin nodes)
  - Contains additional integration tests that don't fit nicely into `ethportal-peertest` (routing table management, etc.)

## `ethportal-peertest`
- A tool to test any client in a cross-client compatible manner
- Contains a set of json fixtures that other clients can pull in to test against

## Todos
- [ ] Common test library to share logic for trin-specific and client-agnostic integration tests
- [ ] Tests directory to hold integration tests
- [ ] Use `match` / something else to validate that every desired endpoint is consistently tested re: https://github.com/ethereum/trin/pull/188/files#r751917711
- [ ] Use ethportal-peertest as a library in tests directory
- [x] Invoke tests directory tests in Circle CI
- [ ] Cross-Client utp tests

**Comment by njgheorghita** [comment]
Closing since test structure is already implemented
